### PR TITLE
Update spellcheck

### PR DESCRIPTION
**Pull request by sjspielman**
Inspired by https://github.com/AlexsLemonade/reproducible-research/actions/runs/8925292477/job/24513633674?pr=162, I've updated to use our spellcheck GHA.

### CODE REVIEW

**Comment by sjspielman** [comment]
Oh dear, what a can of worms 🥴 
Maybe let's just check `docs` 😬

**Comment by jashapiro** [comment]
> Oh dear, what a can of worms 🥴 Maybe let's just check `docs` 😬

Looks like most of the problems are in the cheatsheets files? maybe skip those? But I saw some real errors in there as well that we would want to fix

**Comment by sjspielman** [comment]
Well now I just want to know what's up with my syntax that it won't just check docs files..?

**Comment by jashapiro** [comment]
RE: [9bda4c9](https://github.com/AlexsLemonade/reproducible-research/pull/163/commits/9bda4c951ef745a4149f73d71027419579d7cee0), I meant not to check the cheatsheets, since there are all kinds of funny formatting in there making for funny partial words.

**Review by jashapiro — APPROVED** [review]
LGTM, but let's file an issue to come back and spell check everything? No reason not to have the other stuff checked as well. Maybe not the cheatsheets, but maybe we are fine with some random partial words being added.

**Pull request merged**
